apiVersion: apps/v1
kind: Deployment
metadata:
  name: bruno-girardi
  namespace: ##K8S_NAMESPACE##
  labels:
    app: bruno-girardi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: bruno-girardi
  template:
    metadata:
      labels:
        app: bruno-girardi
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
      - name: bruno-girardi
        image: docker.io/##DOCKER_USERNAME##/satc-devops:##K8S_TAG##
        ports:
        - containerPort: 5173
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bruno-girardi
  namespace: ##K8S_NAMESPACE##
  labels:
    app: bruno-girardi
spec:
  type: ClusterIP
  selector:
    app: bruno-girardi
  ports:
  - port: 80
    targetPort: 5173
    name: http
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-satc
  namespace: ##K8S_NAMESPACE##
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: ##DOCKER_USERNAME##.app.devops-satc.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bruno-girardi
            port:
              number: 80
